language: node_js
node_js:
- '6'
- '7'
- '8'
- '9'
- '10'
cache:
  yarn: true
  directories:
  - node_modules
script: yarn test:ci
before_deploy:
- yarn build
deploy:
  provider: npm
  skip_cleanup: true
  email: benjamin.otto@style-systems.de
  api_key:
    secure: riRlLdArqLnHXcjfKRBdhNLYKg4Swgq6aMlrU9hfiZuwc1rnZlFJwCW8CVE7bUokKoHdfvg1JHBwlAvS4Sy7IvQ8555kYe3vRw3cm/NBLtPLh6lBye3uE/DYovYDgx9adA3WUtzwYSpV9nKFtUx9io1m/f36VOF9xCHg82aFLU+RJr1llyseK+6ZyGvacxQqeSKeprzdTz2GFuXO4Bu2ogwAZ0G+L3gsQieXVsaYCgmLtY/xP6DlhaPcjb6MynVKv9Yh4H0RmyJ/PHaLWC1ff4zkkcyaE1AuB7CuQADmqktc+kTiXh/OeVeHDoPdAw0RDHPc6H7QxsOLBOhG5Ick5sw+lAvZfZQJS23phIo/DjfLm+bxbiYiQN+lCv+5UepCgBVtYXxOWifmwNbYfNlTXwvbE6vioOreJUEU4hCGEp4MW6sNYMxrQ1SKStQc0YUJ3OTIsHMPaZko6XLFhzfflln+yOS4vlsQX3ntMWEA6AMFR7dqKPMpMyi1UGJoI6pXy/d7QeZdEP/deO91tZpOtTnfWMWtGFLg4teEJIM7Ct0rmlputHVG1MTdmYkMvhmSQZlv8y/qncnVFuDYftBBUhITGoycJai9wI0MbR2UkVUpsZw4fFtbc9dUwhDk7pdGy4/Xz7xm3AbB85tqx8I7SEc6f4VKMh3ssaPDw0pQRio=
  on:
    tags: true
    repo: otbe/di
